import Nav from '../components/Nav';


export const metadata = {
  title: 'Skoolworkshop Opslagbeheer',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Nav />

        {children}
        </body>
    </html>
  )
}
